### PR TITLE
use zmq_errno instead of errno for reading the value

### PR DESCRIPTION
**Pull request by tarballs-are-good**
This doesn't fully address the TODO in the source file, but it improves the stability of error handling in multiple threads, by using zmq_errno instead of errno.

### CODE REVIEW

**Comment by orivej** [comment]
Could you provide some details about the motivation for this change: how did you notice that error handling was not stable? Do you think that @7max [TODO comment](https://github.com/orivej/pzmq/blob/master/c-api.lisp#L31-L35) is wrong, or are you making this change for non-glibc based systems?

**Comment by tarballs-are-good** [comment]
I was making this change for non-glibc systems. I’m running on MacOS Sierra with Homebrew-installed zeromq.

The change should be fully backwards compatible. It still has to set the value of errno to 0 before a foreign call is made, which I don’t think works correctly, but at least _getting_ the error works, making it print nicely.

**Comment by tarballs-are-good** [comment]
Maybe this wasn’t clear: the bug I was observing is that every error printed was 0: undefined error. This is basically what the TODO suggests would happen.

**Comment by orivej** [comment]
OK, thank you, could you try this instead: https://github.com/orivej/pzmq/commit/errno

**Comment by orivej** [comment]
I have tested my change with:
```lisp
(asdf:test-system :pzmq-examples)
(in-package :pzmq-examples)
(bordeaux-threads:make-thread 'wuserver)
(wuclient) ; should finish
(setf pzmq:*restart-interrupted-calls* nil)
(wuclient) ; should error
```

**Comment by tarballs-are-good** [comment]
Looks good to me!

**Pull request closed without merging**
