### PR TITLE
Add CurveZMQ support

### LINKED ISSUE #31: Add CurveZMQ support
http://curvezmq.org/

This requires the following C functions to be defined (and possibly wrapped in Lisp codr in order to avoid the Z85 binary encoding):

* `zmq_z85_encode`
* `zmq_z85_decode`
* `zmq_curve_keypair`

### PR DESCRIPTION
**Pull request by phoe**
Fixes #31.

(Note that I've based this PR atop my previous one to make use of `RECV-OCTETS` that I've added there.)

### CODE REVIEW

**Comment by phoe** [comment]
Rebased on top of the current master branch.

**Comment by phoe** [comment]
This PR has not been touched in a while, so here is a cat picture.

**Comment by phoe** [comment]
Bump.

**Comment by orivej** [comment]
I'm very sorry for the delay! Thank you for your contribution, patience, and the cat!

**Comment by phoe** [comment]
Thanks as well!

**Pull request merged**
